2024-10-16 09:34:53,384 INFO    MainThread:34940 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-10-16 09:34:53,384 INFO    MainThread:34940 [wandb_setup.py:_flush():76] Configure stats pid to 34940
2024-10-16 09:34:53,384 INFO    MainThread:34940 [wandb_setup.py:_flush():76] Loading settings from C:\Users\giova\.config\wandb\settings
2024-10-16 09:34:53,384 INFO    MainThread:34940 [wandb_setup.py:_flush():76] Loading settings from C:\Users\giova\__PRODUCTIVITY\ArtificialIntelligence\__UNI\PW_AutonomousAgents\wandb\settings
2024-10-16 09:34:53,384 INFO    MainThread:34940 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-10-16 09:34:53,384 INFO    MainThread:34940 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'C:\\Users\\giova\\__PRODUCTIVITY\\ArtificialIntelligence\\__UNI\\PW_AutonomousAgents\\main.py', 'program': 'C:\\Users\\giova\\__PRODUCTIVITY\\ArtificialIntelligence\\__UNI\\PW_AutonomousAgents\\main.py'}
2024-10-16 09:34:53,385 INFO    MainThread:34940 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\giova\__PRODUCTIVITY\ArtificialIntelligence\__UNI\PW_AutonomousAgents\wandb\run-20241016_093453-j323zydg\logs\debug.log
2024-10-16 09:34:53,385 INFO    MainThread:34940 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\giova\__PRODUCTIVITY\ArtificialIntelligence\__UNI\PW_AutonomousAgents\wandb\run-20241016_093453-j323zydg\logs\debug-internal.log
2024-10-16 09:34:53,385 INFO    MainThread:34940 [wandb_init.py:init():564] calling init triggers
2024-10-16 09:34:53,385 INFO    MainThread:34940 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'num_vehicles': 2, 'vehicles_length': 4, 'num_timesteps': 100, 'T': 0.1, 'tau': 0.1, 'h': 1.5, 'ep_max': 2, 'ep_max_nominal': 15, 'ev_max': 1.5, 'ev_max_nominal': 10, 'acc_min': -2.6, 'acc_max': 2.6, 'u_min': -2.6, 'u_max': 2.6, 'a': 0.1, 'b': 0.1, 'c': 0.2, 'reward_threshold': -0.4483, 'lambd': 0.005, 'env_gamma': 1, 'r': 2, 'leader_min_speed': 50, 'leader_max_speed': 50, 'min_safe_distance': 0.3, 'collision_penalty': -2, 'hidden_size': [256, 128], 'action_size': 200, 'state_bins': (50, 50, 50), 'lr': 0.005, 'agent_gamma': 0.99, 'soft_update_tau': 0.01, 'epsilon': 1.0, 'eps_decay': 0.9999, 'min_epsilon': 0.01, 'buffer_size': 100000, 'batch_size': 128, 'update_freq': 4}
2024-10-16 09:34:53,385 INFO    MainThread:34940 [wandb_init.py:init():614] starting backend
2024-10-16 09:34:53,385 INFO    MainThread:34940 [wandb_init.py:init():618] setting up manager
2024-10-16 09:34:53,387 INFO    MainThread:34940 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-10-16 09:34:53,389 INFO    MainThread:34940 [wandb_init.py:init():624] backend started and connected
2024-10-16 09:34:53,392 INFO    MainThread:34940 [wandb_init.py:init():716] updated telemetry
2024-10-16 09:34:53,470 INFO    MainThread:34940 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-10-16 09:34:54,057 INFO    MainThread:34940 [wandb_run.py:_on_init():2254] communicating current version
2024-10-16 09:34:54,442 INFO    MainThread:34940 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.18.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-10-16 09:34:54,442 INFO    MainThread:34940 [wandb_init.py:init():800] starting run threads in backend
2024-10-16 09:35:19,860 INFO    MainThread:34940 [wandb_run.py:_console_start():2233] atexit reg
2024-10-16 09:35:19,861 INFO    MainThread:34940 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-10-16 09:35:19,862 INFO    MainThread:34940 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-10-16 09:35:19,863 INFO    MainThread:34940 [wandb_run.py:_redirect():2178] Redirects installed.
2024-10-16 09:35:19,868 INFO    MainThread:34940 [wandb_init.py:init():841] run started, returning control to user process
2024-10-16 09:40:48,102 WARNING MsgRouterThr:34940 [router.py:message_loop():77] message_loop has been closed
